name: bioml
channels:
  - bioconda
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - accelerate=1.5.2
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.11.16
  - aiosignal=1.3.2
  - alembic=1.15.2
  - aria2=1.37.0
  - attrs=25.3.0
  - aws-c-auth=0.7.31
  - aws-c-cal=0.7.4
  - aws-c-common=0.9.29
  - aws-c-compression=0.2.19
  - aws-c-event-stream=0.4.3
  - aws-c-http=0.8.10
  - aws-c-io=0.14.19
  - aws-c-mqtt=0.10.7
  - aws-c-s3=0.6.7
  - aws-c-sdkutils=0.1.19
  - aws-checksums=0.1.20
  - aws-crt-cpp=0.28.3
  - aws-sdk-cpp=1.11.407
  - azure-core-cpp=1.13.0
  - azure-identity-cpp=1.8.0
  - azure-storage-blobs-cpp=12.12.0
  - azure-storage-common-cpp=12.7.0
  - azure-storage-files-datalake-cpp=12.11.0
  - bcrypt=4.3.0
  - biopython=1.85
  - blinker=1.9.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.1.31
  - cachetools=5.5.2
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - click=8.1.8
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - colorlog=6.9.0
  - contourpy=1.3.1
  - cpython=3.11.11
  - cryptography=44.0.2
  - cycler=0.12.1
  - databricks-sdk=0.49.0
  - datasets=3.5.0
  - deprecated=1.2.18
  - dill=0.3.8
  - docker-py=7.1.0
  - entrypoints=0.4
  - et_xmlfile=2.0.0
  - exceptiongroup=1.2.2
  - expat=2.7.0
  - filelock=3.18.0
  - fonttools=4.57.0
  - freetype=2.13.3
  - frozenlist=1.5.0
  - fsspec=2024.12.0
  - gawk=5.3.1
  - gflags=2.2.2
  - gitdb=4.0.12
  - gitpython=3.1.44
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.1.5
  - google-auth=2.38.0
  - graphene=3.4.3
  - graphql-core=3.2.6
  - graphql-relay=3.2.0
  - greenlet=3.1.1
  - gunicorn=22.0.0
  - h2=4.2.0
  - hpack=4.1.0
  - huggingface_hub=0.30.1
  - hyperframe=6.1.0
  - idna=3.10
  - importlib-metadata=8.6.1
  - iniconfig=2.0.0
  - itsdangerous=2.2.0
  - jinja2=3.1.6
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libabseil=20240116.2
  - libarrow=17.0.0
  - libarrow-acero=17.0.0
  - libarrow-dataset=17.0.0
  - libarrow-substrait=17.0.0
  - libasprintf=0.23.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.13.0
  - libdb=6.2.32
  - libdeflate=1.23
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.0
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgettextpo=0.23.1
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - libgoogle-cloud=2.29.0
  - libgoogle-cloud-storage=2.29.0
  - libgrpc=1.62.2
  - libiconv=1.18
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblzma=5.6.4
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libopenblas=0.3.29
  - libparquet=17.0.0
  - libpng=1.6.47
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsodium=1.0.20
  - libsqlite=3.49.1
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libthrift=0.20.0
  - libtiff=4.7.0
  - libtorch=2.4.1
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libuv=1.50.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.13.7
  - libzlib=1.3.1
  - lightning=2.5.1
  - lightning-utilities=0.14.3
  - llvmlite=0.44.0
  - lz4-c=1.9.4
  - mako=1.3.9
  - markdown=3.6
  - markupsafe=3.0.2
  - mlflow=2.16.0
  - mlflow-skinny=2.16.0
  - mlflow-ui=2.16.0
  - mmseqs2=17.b804f
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.2.0
  - multiprocess=0.70.16
  - munkres=1.1.4
  - ncurses=6.5
  - networkx=3.4.2
  - nomkl=1.0
  - numba=0.61.0
  - openjpeg=2.5.3
  - openpyxl=3.1.5
  - openssl=3.4.1
  - opentelemetry-api=1.31.1
  - opentelemetry-sdk=1.31.1
  - opentelemetry-semantic-conventions=0.52b1
  - optuna=4.2.1
  - optuna-integration=4.2.1
  - orc=2.0.2
  - packaging=24.2
  - paramiko=3.5.1
  - peft=0.15.0
  - perl=5.32.1
  - perl-base=2.23
  - perl-bio-featureio=1.6.905
  - perl-bioperl-core=1.7.8
  - perl-business-isbn=3.007
  - perl-business-isbn-data=20210112.006
  - perl-carp=1.50
  - perl-compress-raw-zlib=2.202
  - perl-constant=1.33
  - perl-data-dump=1.25
  - perl-db_file=1.858
  - perl-digest-hmac=1.04
  - perl-digest-md5=2.59
  - perl-encode=3.21
  - perl-encode-locale=1.05
  - perl-exporter=5.74
  - perl-extutils-makemaker=7.70
  - perl-file-listing=6.16
  - perl-file-slurp-tiny=0.004
  - perl-file-spec=3.48_01
  - perl-html-parser=3.83
  - perl-html-tagset=3.20
  - perl-http-cookies=6.10
  - perl-http-daemon=6.16
  - perl-http-date=6.06
  - perl-http-message=6.36
  - perl-http-negotiate=6.01
  - perl-io-html=1.004
  - perl-io-socket-ssl=2.075
  - perl-libwww-perl=6.68
  - perl-libxml-perl=0.08
  - perl-lwp-mediatypes=6.04
  - perl-lwp-protocol-https=6.10
  - perl-mime-base64=3.16
  - perl-module-load=0.34
  - perl-mozilla-ca=20211001
  - perl-net-http=6.22
  - perl-net-ssleay=1.94
  - perl-ntlm=1.09
  - perl-parent=0.243
  - perl-socket=2.027
  - perl-storable=3.15
  - perl-test-fatal=0.016
  - perl-test-requiresinternet=0.05
  - perl-test-warnings=0.031
  - perl-time-local=1.35
  - perl-timedate=2.33
  - perl-tree-dag_node=1.32
  - perl-try-tiny=0.31
  - perl-uri=5.17
  - perl-url-encode=0.03
  - perl-www-robotrules=6.02
  - perl-xml-dom=1.46
  - perl-xml-dom-xpath=0.14
  - perl-xml-parser=2.44_01
  - perl-xml-regexp=0.04
  - perl-xml-xpathengine=0.14
  - pillow=11.1.0
  - pip=25.0.1
  - pluggy=1.5.0
  - prometheus_client=0.21.1
  - prometheus_flask_exporter=0.23.2
  - propcache=0.2.1
  - protobuf=4.25.3
  - psutil=7.0.0
  - pthread-stubs=0.4
  - pyarrow=17.0.0
  - pyarrow-core=17.0.0
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.2
  - pycparser=2.22
  - pynacl=1.5.0
  - pyod=2.0.4
  - pyopenssl=25.0.0
  - pyparsing=3.2.3
  - pysocks=1.7.1
  - pytest=8.3.5
  - python=3.11.11
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python-xxhash=3.5.0
  - python_abi=3.11
  - pytorch=2.4.1
  - pytorch-lightning=2.5.1
  - pytz=2024.2
  - pyu2f=0.1.5
  - pywin32-on-windows=0.1.0
  - pyyaml=6.0.2
  - qhull=2020.2
  - querystring_parser=1.2.4
  - re2=2023.09.01
  - readline=8.2
  - regex=2024.11.6
  - requests=2.32.3
  - rsa=4.9
  - s2n=1.5.5
  - safetensors=0.5.3
  - setuptools=75.8.2
  - six=1.17.0
  - sleef=3.8
  - smmap=5.0.2
  - snappy=1.2.1
  - sqlalchemy=2.0.40
  - sqlparse=0.5.3
  - sympy=1.13.3
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tokenizers=0.21.1
  - tomli=2.2.1
  - torchmetrics=1.7.0
  - tqdm=4.67.1
  - transformers=4.50.0
  - typing-extensions=4.13.0
  - typing_extensions=4.13.0
  - tzdata=2025b
  - unicodedata2=16.0.0
  - urllib3=2.3.0
  - websocket-client=1.8.0
  - wheel=0.45.1
  - wrapt=1.17.2
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xxhash=0.8.3
  - yaml=0.2.5
  - yarl=1.18.3
  - zipp=3.21.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - adagio==0.2.6
      - annotated-types==0.7.0
      - ansi2html==1.9.2
      - aplr==10.8.0
      - appdirs==1.4.4
      - asttokens==3.0.0
      - bioml==1.0.0
      - catboost==1.2.7
      - category-encoders==2.7.0
      - colour==0.1.5
      - combo==0.1.3
      - comm==0.2.2
      - cython==3.0.12
      - daal==2025.4.0
      - dacite==1.9.2
      - dash==2.18.2
      - dash-auth==2.3.0
      - dash-bootstrap-components==1.7.1
      - dash-core-components==2.0.0
      - dash-cytoscape==1.0.2
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - debugpy==1.8.13
      - decorator==5.2.1
      - deprecation==2.1.0
      - dtreeviz==2.2.2
      - executing==2.2.0
      - explainerdashboard==0.4.8
      - fairlearn==0.7.0
      - fastjsonschema==2.21.1
      - flask==3.0.3
      - flask-simplelogin==0.2.0
      - flask-wtf==1.2.2
      - fs==2.4.16
      - fugue==0.9.1
      - gevent==24.11.1
      - htmlmin==0.1.12
      - imagehash==4.3.1
      - imbalanced-learn==0.13.0
      - interpret==0.6.10
      - interpret-core==0.6.10
      - ipykernel==6.29.5
      - ipython==9.0.2
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.5
      - jedi==0.19.2
      - joblib==1.3.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyter-dash==0.4.2
      - jupyterlab-widgets==3.0.13
      - kaleido==0.2.1
      - kmodes==0.12.2
      - lightgbm==4.6.0
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - mlxtend==0.23.4
      - multimethod==1.12
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - numpy==1.26.4
      - nvidia-nccl-cu12==2.26.2
      - orjson==3.10.16
      - oyaml==1.0
      - pandas==2.1.4
      - parso==0.8.4
      - patsy==1.0.1
      - pexpect==4.9.0
      - phik==0.12.4
      - platformdirs==4.3.7
      - plotly==5.24.1
      - plotly-resampler==0.10.0
      - pmdarima==2.0.4
      - prompt-toolkit==3.0.50
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - puremagic==1.28
      - pycaret==3.3.2
      - pydantic==2.11.2
      - pydantic-core==2.33.1
      - pygments==2.19.1
      - pynndescent==0.5.13
      - python-graphviz==0.20.3
      - pywavelets==1.8.0
      - pyzmq==26.3.0
      - referencing==0.36.2
      - retrying==1.3.4
      - rpds-py==0.24.0
      - salib==1.5.1
      - schemdraw==0.15
      - scikit-base==0.7.8
      - scikit-learn==1.4.2
      - scikit-learn-intelex==2025.4.0
      - scikit-plot==0.3.7
      - scipy==1.11.4
      - seaborn==0.13.2
      - shap==0.44.1
      - sklearn-compat==0.1.3
      - sktime==0.26.0
      - slicer==0.0.7
      - stack-data==0.6.3
      - statsforecast==1.5.0
      - statsmodels==0.14.4
      - tbats==1.1.3
      - tbb==2022.1.0
      - tcmlib==1.3.0
      - tenacity==9.1.2
      - tornado==6.4.2
      - traitlets==5.14.3
      - triad==0.9.8
      - tsdownsample==0.1.4.1
      - typeguard==4.4.2
      - typing-inspection==0.4.0
      - umap-learn==0.5.7
      - visions==0.8.1
      - waitress==3.0.2
      - wcwidth==0.2.13
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.13
      - wordcloud==1.9.4
      - wtforms==3.2.1
      - wurlitzer==3.1.1
      - xgboost==3.0.0
      - ydata-profiling==4.16.1
      - yellowbrick==1.5
      - zope-event==5.0
      - zope-interface==7.2
