name: bioml_pycaret
channels:
  - bioconda
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alembic=1.13.1
  - anyio=4.2.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - aria2=1.37.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - attrs=23.2.0
  - aws-c-auth=0.7.11
  - aws-c-cal=0.6.9
  - aws-c-common=0.9.12
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.4.1
  - aws-c-http=0.8.0
  - aws-c-io=0.14.0
  - aws-c-mqtt=0.10.1
  - aws-c-s3=0.4.9
  - aws-c-sdkutils=0.1.13
  - aws-checksums=0.1.17
  - aws-crt-cpp=0.26.0
  - aws-sdk-cpp=1.11.210
  - babel=2.14.0
  - banal=1.0.6
  - bcrypt=4.1.2
  - beautifulsoup4=4.12.2
  - biopython=1.83
  - bleach=6.1.0
  - blinker=1.7.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.25.0
  - ca-certificates=2024.2.2
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - colorlog=6.8.0
  - comm=0.2.1
  - configparser=5.3.0
  - contourpy=1.2.0
  - cryptography=41.0.7
  - cycler=0.12.1
  - databricks-cli=0.18.0
  - dataset=1.6.2
  - debugpy=1.8.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - docker-py=6.1.3
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - fonttools=4.47.2
  - fqdn=1.5.1
  - freetype=2.12.1
  - gawk=5.3.0
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gflags=2.2.2
  - gitdb=4.0.11
  - gitpython=3.1.41
  - glog=0.6.0
  - gmp=6.3.0
  - greenlet=3.0.3
  - gunicorn=21.2.0
  - icu=73.2
  - idna=3.6
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - importlib_resources=6.1.1
  - ipykernel=6.28.0
  - ipython=8.20.0
  - isoduration=20.11.0
  - itsdangerous=2.1.2
  - jedi=0.19.1
  - jinja2=3.1.3
  - joblib=1.3.2
  - json5=0.9.14
  - jsonpointer=2.4
  - jsonschema=4.20.0
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.20.0
  - jupyter-lsp=2.2.1
  - jupyter_client=8.6.0
  - jupyter_core=5.7.1
  - jupyter_events=0.9.0
  - jupyter_server=2.12.4
  - jupyter_server_terminals=0.5.1
  - jupyterlab=4.0.10
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.25.2
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20230802.1
  - libarrow=14.0.2
  - libarrow-acero=14.0.2
  - libarrow-dataset=14.0.2
  - libarrow-flight=14.0.2
  - libarrow-flight-sql=14.0.2
  - libarrow-gandiva=14.0.2
  - libarrow-substrait=14.0.2
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.5.0
  - libdeflate=1.19
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=13.2.0
  - libgoogle-cloud=2.12.0
  - libgrpc=1.59.3
  - libiconv=1.17
  - libidn2=2.3.7
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libllvm15=15.0.7
  - libnghttp2=1.58.0
  - libnl=3.9.0
  - libnsl=2.0.1
  - libnuma=2.0.16
  - libopenblas=0.3.25
  - libparquet=14.0.2
  - libpng=1.6.39
  - libprotobuf=4.24.4
  - libre2-11=2023.06.02
  - libsodium=1.0.18
  - libsqlite=3.44.2
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libunistring=0.9.10
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxml2=2.12.3
  - libzlib=1.2.13
  - llvmlite=0.41.1
  - lz4-c=1.9.4
  - mako=1.3.0
  - markdown=3.5.2
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.6
  - mistune=3.0.2
  - mlflow=2.9.2
  - mmseqs2=15.6f452
  - mpfr=4.2.1
  - munkres=1.1.4
  - nbclient=0.8.0
  - nbconvert-core=7.14.1
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.5.8
  - notebook=7.0.6
  - notebook-shim=0.2.3
  - numba=0.58.1
  - oauthlib=3.2.2
  - openjpeg=2.5.0
  - openpyxl=3.1.2
  - openssl=3.3.0
  - optuna=3.5.0
  - orc=1.9.2
  - overrides=7.4.0
  - packaging=23.2
  - pandocfilters=1.5.0
  - paramiko=3.4.0
  - parso=0.8.3
  - patsy=0.5.6
  - perl=5.32.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.2.0
  - pip=23.3.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.1.0
  - prometheus_client=0.19.0
  - prometheus_flask_exporter=0.23.0
  - prompt-toolkit=3.0.42
  - protobuf=4.24.4
  - psutil=5.9.7
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=14.0.2
  - pycparser=2.21
  - pygments=2.17.2
  - pyjwt=2.8.0
  - pynacl=1.5.0
  - pyod=1.1.3
  - pyparsing=3.1.1
  - pysocks=1.7.1
  - python=3.10.13
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.19.1
  - python-json-logger=2.0.7
  - python-tzdata=2023.4
  - python_abi=3.10
  - pytz=2023.3.post1
  - pywin32-on-windows=0.1.0
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - querystring_parser=1.2.4
  - rdma-core=49.0
  - re2=2023.06.02
  - readline=8.2
  - referencing=0.32.1
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.16.2
  - s2n=1.4.1
  - send2trash=1.8.2
  - setuptools=69.0.3
  - shap=0.44.0
  - six=1.16.0
  - slicer=0.0.7
  - smmap=5.0.0
  - snappy=1.1.10
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlalchemy=1.4.49
  - sqlparse=0.4.4
  - stack_data=0.6.2
  - statsmodels=0.14.1
  - tabulate=0.9.0
  - terminado=0.18.0
  - threadpoolctl=3.2.0
  - tinycss2=1.2.1
  - tk=8.6.13
  - tomli=2.0.1
  - tornado=6.3.3
  - tqdm=4.66.1
  - traitlets=5.14.1
  - types-python-dateutil=2.8.19.20240106
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - typing_utils=0.1.0
  - tzdata=2023d
  - ucx=1.15.0
  - unicodedata2=15.1.0
  - uri-template=1.3.0
  - urllib3=2.1.0
  - wcwidth=0.2.13
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.7.0
  - werkzeug=3.0.1
  - wget=1.21.4
  - wheel=0.42.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - accelerate==0.26.1
      - adagio==0.2.4
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - annotated-types==0.6.0
      - ansi2html==1.9.1
      - antlr4-python3-runtime==4.11.1
      - appdirs==1.4.4
      - async-timeout==4.0.3
      - bioml==1.0.0
      - catboost==1.2.2
      - category-encoders==2.6.3
      - colour==0.1.5
      - combo==0.1.3
      - cython==3.0.8
      - daal==2024.0.1
      - daal4py==2024.0.1
      - dacite==1.8.1
      - dash==2.14.2
      - dash-auth==2.0.0
      - dash-bootstrap-components==1.5.0
      - dash-core-components==2.0.0
      - dash-cytoscape==0.3.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - datasets==2.19.1
      - deprecated==1.2.14
      - deprecation==2.1.0
      - dill==0.3.7
      - dtreeviz==2.2.2
      - explainerdashboard==0.4.5
      - fairlearn==0.7.0
      - filelock==3.13.1
      - flask==2.2.3
      - flask-simplelogin==0.1.2
      - flask-wtf==1.2.1
      - frozenlist==1.4.1
      - fs==2.4.16
      - fsspec==2023.12.2
      - fugue==0.8.7
      - fugue-sql-antlr==0.2.0
      - gevent==23.9.1
      - htmlmin==0.1.12
      - huggingface-hub==0.23.0
      - imagehash==4.3.1
      - imbalanced-learn==0.11.0
      - iniconfig==2.0.0
      - interpret==0.5.0
      - interpret-core==0.5.0
      - ipywidgets==8.1.1
      - jupyter-dash==0.4.2
      - jupyterlab-widgets==3.0.9
      - kaleido==0.2.1
      - kmodes==0.12.2
      - lightgbm==4.2.0
      - matplotlib==3.6.0
      - mlxtend==0.23.1
      - mpmath==1.3.0
      - multidict==6.0.5
      - multimethod==1.10
      - multiprocess==0.70.15
      - networkx==3.2.1
      - numpy==1.25.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - orjson==3.9.10
      - oyaml==1.0
      - pandas==1.5.3
      - phik==0.12.4
      - plotly==5.18.0
      - plotly-resampler==0.9.1
      - pluggy==1.3.0
      - pmdarima==2.0.4
      - pyarrow-hotfix==0.6
      - pycaret==3.2.0
      - pydantic==2.5.3
      - pydantic-core==2.14.6
      - pynndescent==0.5.11
      - pytest==7.4.4
      - python-graphviz==0.20.1
      - pywavelets==1.5.0
      - qpd==0.4.4
      - regex==2023.12.25
      - retrying==1.3.4
      - safetensors==0.4.1
      - salib==1.4.7
      - schemdraw==0.15
      - scikit-base==0.5.2
      - scikit-learn==1.2.2
      - scikit-learn-intelex==2024.0.1
      - scikit-plot==0.3.7
      - scipy==1.10.1
      - seaborn==0.12.2
      - sktime==0.21.1
      - sqlglot==20.8.0
      - statsforecast==1.5.0
      - sympy==1.12
      - tangled-up-in-unicode==0.2.0
      - tbats==1.1.3
      - tbb==2021.11.0
      - tenacity==8.2.3
      - tokenizers==0.15.0
      - torch==2.1.2
      - trace-updater==0.0.9.1
      - transformers==4.36.2
      - triad==0.9.3
      - triton==2.1.0
      - tsdownsample==0.1.2
      - typeguard==4.1.5
      - umap-learn==0.5.5
      - visions==0.7.5
      - waitress==2.1.2
      - widgetsnbextension==4.0.9
      - wordcloud==1.9.3
      - wrapt==1.16.0
      - wtforms==3.1.2
      - wurlitzer==3.0.3
      - xgboost==2.0.3
      - xxhash==3.4.1
      - yarl==1.9.4
      - ydata-profiling==4.6.4
      - yellowbrick==1.5
      - zope-event==5.0
      - zope-interface==6.1
      - lightning
