name: bioml
channels:
  - bioconda
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - accelerate=1.3.0
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.10.5
  - aiosignal=1.3.2
  - alembic=1.14.1
  - alsa-lib=1.2.13
  - annotated-types=0.7.0
  - anyio=4.8.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - aria2=1.37.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.4
  - attrs=25.1.0
  - aws-c-auth=0.8.1
  - aws-c-cal=0.8.1
  - aws-c-common=0.10.6
  - aws-c-compression=0.3.0
  - aws-c-event-stream=0.5.0
  - aws-c-http=0.9.2
  - aws-c-io=0.15.3
  - aws-c-mqtt=0.11.0
  - aws-c-s3=0.7.9
  - aws-c-sdkutils=0.2.2
  - aws-checksums=0.2.2
  - aws-crt-cpp=0.29.9
  - aws-sdk-cpp=1.11.489
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - babel=2.17.0
  - bcrypt=4.2.1
  - beautifulsoup4=4.13.3
  - biopython=1.85
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - blinker=1.9.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.1.31
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.5.1
  - cairo=1.18.2
  - certifi=2024.12.14
  - cffi=1.17.1
  - chardet=5.2.0
  - charset-normalizer=3.4.1
  - click=8.1.8
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - colorlog=6.9.0
  - comm=0.2.2
  - contourpy=1.3.1
  - cpython=3.11.11
  - cryptography=44.0.0
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - databricks-sdk=0.43.0
  - datasets=3.2.0
  - dbus=1.13.6
  - debugpy=1.8.12
  - decorator=5.1.1
  - defusedxml=0.7.1
  - deprecated=1.2.18
  - dill=0.3.8
  - docker-py=7.1.0
  - double-conversion=3.3.0
  - entrypoints=0.4
  - et_xmlfile=2.0.0
  - exceptiongroup=1.2.2
  - expat=2.6.4
  - filelock=3.17.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.55.8
  - fqdn=1.5.1
  - freetype=2.12.1
  - freetype-py=2.3.0
  - frozenlist=1.5.0
  - fsspec=2024.9.0
  - gawk=5.3.1
  - gflags=2.2.2
  - gitdb=4.0.12
  - gitpython=3.1.44
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.1.5
  - google-auth=2.38.0
  - graphene=3.4.3
  - graphite2=1.3.13
  - graphql-core=3.2.6
  - graphql-relay=3.2.0
  - greenlet=3.1.1
  - grpcio=1.67.1
  - gunicorn=23.0.0
  - h11=0.14.0
  - h2=4.2.0
  - harfbuzz=10.2.0
  - hpack=4.1.0
  - httpcore=1.0.7
  - httpx=0.28.1
  - huggingface_hub=0.28.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.6.1
  - importlib_resources=6.5.2
  - iniconfig=2.0.0
  - ipykernel=6.29.5
  - ipython=8.32.0
  - isoduration=20.11.0
  - itsdangerous=2.2.0
  - jedi=0.19.2
  - jinja2=3.1.5
  - json5=0.10.0
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.3.5
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.16
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libabseil=20240722.0
  - libarrow=18.1.0
  - libarrow-acero=18.1.0
  - libarrow-dataset=18.1.0
  - libarrow-substrait=18.1.0
  - libasprintf=0.22.5
  - libblas=3.9.0
  - libboost=1.86.0
  - libboost-python=1.86.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp19.1=19.1.7
  - libclang13=19.1.7
  - libcrc32c=1.1.2
  - libcups=2.3.3
  - libcurl=8.11.1
  - libdb=6.2.32
  - libdeflate=1.23
  - libdrm=2.4.124
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgettextpo=0.22.5
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgl=1.7.0
  - libglib=2.82.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgoogle-cloud=2.34.0
  - libgoogle-cloud-storage=2.34.0
  - libgrpc=1.67.1
  - libhwloc=2.11.2
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm15=15.0.7
  - libllvm19=19.1.7
  - liblzma=5.6.4
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libopengl=1.7.0
  - libparquet=18.1.0
  - libpciaccess=0.18
  - libpng=1.6.46
  - libpq=17.2
  - libprotobuf=5.28.3
  - librdkit=2024.09.5
  - libre2-11=2024.07.02
  - libsodium=1.0.20
  - libsqlite=3.48.0
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libtorch=2.5.1
  - libutf8proc=2.10.0
  - libuuid=2.38.1
  - libuv=1.50.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.8.0
  - libxml2=2.13.5
  - libxslt=1.1.39
  - libzlib=1.3.1
  - lightning=2.5.0.post0
  - lightning-utilities=0.12.0
  - llvm-openmp=19.1.7
  - llvmlite=0.44.0
  - lz4-c=1.10.0
  - mako=1.3.9
  - markdown=3.6
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - mistune=3.1.1
  - mkl=2024.2.2
  - mlflow=2.20.1
  - mlflow-skinny=2.20.1
  - mlflow-ui=2.20.1
  - mmseqs2=17.b804f
  - modin-core=0.32.0
  - modin-ray=0.32.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - msgpack-python=1.1.0
  - multidict=6.1.0
  - multiprocess=0.70.16
  - munkres=1.0.7
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - notebook=7.3.2
  - notebook-shim=0.2.4
  - numba=0.61.0
  - numpy=1.26.4
  - openjpeg=2.5.3
  - openldap=2.6.9
  - openpyxl=3.1.5
  - openssl=3.4.0
  - opentelemetry-api=1.16.0
  - opentelemetry-sdk=1.16.0
  - opentelemetry-semantic-conventions=0.37b0
  - optuna=4.2.0
  - optuna-integration=4.2.1
  - orc=2.0.3
  - overrides=7.7.0
  - packaging=24.2
  - pandocfilters=1.5.0
  - paramiko=3.5.1
  - parso=0.8.4
  - patsy=1.0.1
  - pcre2=10.44
  - peft=0.14.0
  - perl=5.32.1
  - perl-base=2.23
  - perl-bio-featureio=1.6.905
  - perl-bioperl-core=1.7.8
  - perl-business-isbn=3.007
  - perl-business-isbn-data=20210112.006
  - perl-carp=1.38
  - perl-compress-raw-zlib=2.105
  - perl-constant=1.33
  - perl-data-dump=1.25
  - perl-data-dumper=2.183
  - perl-db_file=1.858
  - perl-digest-hmac=1.04
  - perl-digest-md5=2.58
  - perl-encode=3.19
  - perl-encode-locale=1.05
  - perl-exporter=5.72
  - perl-extutils-makemaker=7.70
  - perl-file-listing=6.16
  - perl-file-slurp-tiny=0.004
  - perl-file-spec=3.48_01
  - perl-html-parser=3.81
  - perl-html-tagset=3.20
  - perl-http-cookies=6.10
  - perl-http-daemon=6.16
  - perl-http-date=6.06
  - perl-http-message=6.36
  - perl-http-negotiate=6.01
  - perl-io-html=1.004
  - perl-io-socket-ssl=2.074
  - perl-libwww-perl=6.68
  - perl-libxml-perl=0.08
  - perl-lwp-mediatypes=6.04
  - perl-lwp-protocol-https=6.10
  - perl-mime-base64=3.16
  - perl-module-load=0.34
  - perl-mozilla-ca=20211001
  - perl-net-http=6.22
  - perl-net-ssleay=1.94
  - perl-ntlm=1.09
  - perl-parent=0.236
  - perl-socket=2.027
  - perl-test-requiresinternet=0.05
  - perl-time-local=1.35
  - perl-timedate=2.33
  - perl-tree-dag_node=1.32
  - perl-try-tiny=0.31
  - perl-uri=5.12
  - perl-url-encode=0.03
  - perl-www-robotrules=6.02
  - perl-xml-dom=1.46
  - perl-xml-dom-xpath=0.14
  - perl-xml-parser=2.44_01
  - perl-xml-regexp=0.04
  - perl-xml-xpathengine=0.14
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.0
  - pixman=0.44.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - pluggy=1.5.0
  - prometheus_client=0.21.1
  - prometheus_flask_exporter=0.23.1
  - prompt-toolkit=3.0.50
  - protobuf=5.28.3
  - psutil=6.1.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=18.1.0
  - pyarrow-core=18.1.0
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.1
  - pybind11=2.13.6
  - pybind11-global=2.13.6
  - pycairo=1.27.0
  - pycparser=2.22
  - pydantic=2.10.6
  - pydantic-core=2.27.2
  - pygments=2.19.1
  - pynacl=1.5.0
  - pyod=2.0.2
  - pyopenssl=25.0.0
  - pyparsing=3.2.1
  - pyside6=6.8.2
  - pysocks=1.7.1
  - pytest=8.3.4
  - python=3.11.11
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python-json-logger=2.0.7
  - python-tzdata=2025.1
  - python-xxhash=3.5.0
  - python_abi=3.11
  - pytorch=2.5.1
  - pytorch-lightning=2.5.0.post0
  - pytz=2024.1
  - pyu2f=0.1.5
  - pywin32-on-windows=0.1.0
  - pyyaml=6.0.2
  - pyzmq=26.2.1
  - qhull=2020.2
  - qt6-main=6.8.2
  - querystring_parser=1.2.4
  - ray-core=2.41.0
  - rdkit=2024.09.5
  - re2=2024.07.02
  - readline=8.2
  - referencing=0.36.2
  - regex=2024.11.6
  - reportlab=4.3.0
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rlpycairo=0.2.0
  - rpds-py=0.22.3
  - rsa=4.9
  - s2n=1.5.11
  - safetensors=0.5.2
  - send2trash=1.8.3
  - setproctitle=1.3.4
  - setuptools=75.8.0
  - six=1.17.0
  - sleef=3.8
  - smmap=5.0.0
  - snappy=1.2.1
  - sniffio=1.3.1
  - soupsieve=2.5
  - sqlalchemy=2.0.37
  - sqlparse=0.5.3
  - stack_data=0.6.3
  - statsmodels=0.14.4
  - sympy=1.13.3
  - terminado=0.18.1
  - threadpoolctl=3.5.0
  - tinycss2=1.4.0
  - tk=8.6.13
  - tokenizers=0.21.0
  - tomli=2.2.1
  - torchmetrics=1.6.1
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - transformers=4.48.2
  - types-python-dateutil=2.9.0.20241206
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzdata=2025a
  - unicodedata2=16.0.0
  - uri-template=1.3.0
  - urllib3=2.3.0
  - wayland=1.23.1
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - wrapt=1.17.2
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.43
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.5
  - xorg-libx11=1.8.11
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xxhash=0.8.2
  - yaml=0.2.5
  - yarl=1.9.4
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - adagio==0.2.6
      - ansi2html==1.9.2
      - aplr==10.8.0
      - appdirs==1.4.4
      - bioml==1.0.0
      - catboost==1.2.7
      - category-encoders==2.7.0
      - colour==0.1.5
      - combo==0.1.3
      - cython==3.0.11
      - daal==2025.1.0
      - dacite==1.9.2
      - dash==2.18.2
      - dash-auth==2.3.0
      - dash-bootstrap-components==1.7.1
      - dash-core-components==2.0.0
      - dash-cytoscape==1.0.2
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - deprecation==2.1.0
      - dtreeviz==2.2.2
      - executing==2.2.0
      - explainerdashboard==0.4.8
      - fairlearn==0.7.0
      - flask==3.0.3
      - flask-simplelogin==0.2.0
      - flask-wtf==1.2.2
      - fs==2.4.16
      - fugue==0.9.1
      - gevent==24.11.1
      - htmlmin==0.1.12
      - ifeatureomegacli==1.0.2
      - imagehash==4.3.1
      - imbalanced-learn==0.13.0
      - interpret==0.6.9
      - interpret-core==0.6.9
      - ipywidgets==8.1.5
      - joblib==1.3.2
      - jupyter-dash==0.4.2
      - jupyterlab-widgets==3.0.13
      - kaleido==0.2.1
      - kmodes==0.12.2
      - lightgbm==4.5.0
      - matplotlib==3.7.5
      - mlxtend==0.23.4
      - multimethod==1.12
      - nvidia-nccl-cu12==2.25.1
      - orjson==3.10.15
      - oyaml==1.0
      - pandas==2.1.4
      - phik==0.12.4
      - plotly==5.24.1
      - plotly-resampler==0.10.0
      - pmdarima==2.0.4
      - pycaret==3.3.2
      - pynndescent==0.5.13
      - python-graphviz==0.20.3
      - pywavelets==1.8.0
      - retrying==1.3.4
      - salib==1.5.1
      - schemdraw==0.15
      - scikit-base==0.7.8
      - scikit-learn==1.4.2
      - scikit-learn-intelex==2025.1.0
      - scikit-plot==0.3.7
      - scipy==1.11.4
      - seaborn==0.13.2
      - shap==0.44.1
      - sklearn-compat==0.1.3
      - sktime==0.26.0
      - slicer==0.0.7
      - statsforecast==1.5.0
      - tbats==1.1.3
      - tbb==2022.0.0
      - tcmlib==1.2.0
      - tenacity==9.0.0
      - triad==0.9.8
      - tsdownsample==0.1.4.1
      - typeguard==4.4.1
      - umap-learn==0.5.7
      - visions==0.7.6
      - waitress==3.0.2
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.13
      - wordcloud==1.9.4
      - wtforms==3.2.1
      - wurlitzer==3.1.1
      - xgboost==2.1.3
      - ydata-profiling==4.12.2
      - yellowbrick==1.5
      - zope-event==5.0
      - zope-interface==7.2
